from sqlalchemy import Column, Integer, String, Text, DateTime, ForeignKey, JSON
from sqlalchemy.orm import relationship
from datetime import datetime
from .database import Base

class Analysis(Base):
    __tablename__ = "analyses"

    id = Column(Integer, primary_key=True, index=True)
    main_url = Column(String, index=True)
    name = Column(String, default="Análisis sin nombre")
    status = Column(String, default="pending")  # pending, processing, completed, failed
    created_at = Column(DateTime, default=datetime.utcnow)
    
    # Global summary generated by Gemini
    global_summary = Column(Text, nullable=True)
    
    reports = relationship("PageReport", back_populates="analysis", cascade="all, delete-orphan")

class PageReport(Base):
    __tablename__ = "page_reports"

    id = Column(Integer, primary_key=True, index=True)
    analysis_id = Column(Integer, ForeignKey("analyses.id"))
    url = Column(String)
    
    # Raw audit data from playwright
    raw_data = Column(JSON)
    
    # Generated by Gemini
    summary_left = Column(Text)  # Critics, Warnings, Good
    action_plan_right = Column(Text)  # Action plan for critics/warnings
    
    analysis = relationship("Analysis", back_populates="reports")
